map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.45 
inflation_radius: 0.8

# footprint: [[-0.4,-0.4],[0.2,-0.4],[0.6,0.0],[0.2,0.4],[-0.4,0.4]]

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: my_bot/laser/scan, marking: true, clearing: true}
